### PR TITLE
Uisp integration 2

### PR DESCRIPTION
**Pull request by thebracket**
Replaced `integrationUISP.py` with a Rust-based system. This has the advantages of being faster and using less resources (38 Mb of RAM on my test system). The emphasis is on correctly determining links in a very complicated network, and not "losing" pass-through connections to customers. It supports flat and "full" strategies, and aims to duplicate most of the original Python functionality.

Please review and test before merging. It's live on my system.

### CODE REVIEW

**Comment by rchac** [comment]
The MikroTik IPv6 pull is working!

Only observable bug left:

If a client site is directly connected to another site through a link, the client's speed is set to the link speed, regardless of that client's actual speed plan assigned in UNMS.
image

**Comment by rchac** [comment]
Hm. Didn't quite fix it. Perhaps it needs to be something like this?
```
IF (Site type is client site):
   maxMbps = MIN(client speed, site speed)
```

**Review by rchac — APPROVED** [review]

**Comment by thebracket** [comment]
Huh. I rebased to `develop` and pushed, and it still complains?

**Comment by thebracket** [comment]
I went through with the manual merge. Once its in develop, I'll fixup the CI - that's partly in another PR (the build one is running afoul of a known bug according to Github's support pages).

**Pull request merged**
